<?xml version="1.0" encoding="utf-8"?>
<Database Name="Consolidated_Test_Data" Class="Con_DB_DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=lvsql;Initial Catalog=Consolidated_Test_Data;Integrated Security=True" SettingsObjectName="New_Analyze_SH.My.MySettings" SettingsPropertyName="Consolidated_Test_DataConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.v_ALF_Data_Is_Null" Member="v_ALF_Data_Is_Nulls">
    <Type Name="v_ALF_Data_Is_Null">
      <Column Name="Record_ID" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ALF_Data" Member="ALF_Datas">
    <Type Name="ALF_Data">
      <Column Name="Record_ID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MeasurementsSuiteID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PartID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PartNumber" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="ArrayNumber" Type="System.String" DbType="NVarChar(13)" CanBeNull="true" />
      <Column Name="PassFailCode" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SiteID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OperatorID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DOYNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="StartDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[06]" Member="_06" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[07]" Member="_07" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[08]" Member="_08" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[09]" Member="_09" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[10]" Member="_10" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[11]" Member="_11" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[12]" Member="_12" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[13]" Member="_13" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[14]" Member="_14" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[15]" Member="_15" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[16]" Member="_16" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[17]" Member="_17" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[18]" Member="_18" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[19]" Member="_19" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[20]" Member="_20" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[21]" Member="_21" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[22]" Member="_22" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[23]" Member="_23" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[24]" Member="_24" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[25]" Member="_25" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[26]" Member="_26" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[27]" Member="_27" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[28]" Member="_28" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[29]" Member="_29" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[30]" Member="_30" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[31]" Member="_31" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[32]" Member="_32" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[33]" Member="_33" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[34]" Member="_34" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[35]" Member="_35" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[36]" Member="_36" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[37]" Member="_37" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[38]" Member="_38" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[39]" Member="_39" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[40]" Member="_40" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[41]" Member="_41" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[42]" Member="_42" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[43]" Member="_43" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[44]" Member="_44" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[45]" Member="_45" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[46]" Member="_46" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[47]" Member="_47" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[48]" Member="_48" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[49]" Member="_49" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[50]" Member="_50" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[51]" Member="_51" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[52]" Member="_52" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[53]" Member="_53" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[54]" Member="_54" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[55]" Member="_55" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[56]" Member="_56" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[57]" Member="_57" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[58]" Member="_58" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[59]" Member="_59" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[60]" Member="_60" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[61]" Member="_61" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[62]" Member="_62" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[63]" Member="_63" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[64]" Member="_64" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[65]" Member="_65" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[66]" Member="_66" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[67]" Member="_67" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[68]" Member="_68" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[69]" Member="_69" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[70]" Member="_70" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[71]" Member="_71" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[72]" Member="_72" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[73]" Member="_73" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[74]" Member="_74" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[75]" Member="_75" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[76]" Member="_76" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[77]" Member="_77" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[78]" Member="_78" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[79]" Member="_79" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[80]" Member="_80" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[81]" Member="_81" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[82]" Member="_82" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[83]" Member="_83" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[84]" Member="_84" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[85]" Member="_85" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[86]" Member="_86" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[87]" Member="_87" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[88]" Member="_88" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[89]" Member="_89" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[90]" Member="_90" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[91]" Member="_91" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[92]" Member="_92" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[93]" Member="_93" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[94]" Member="_94" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[95]" Member="_95" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[96]" Member="_96" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[97]" Member="_97" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[98]" Member="_98" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[99]" Member="_99" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[100]" Member="_100" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[101]" Member="_101" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[102]" Member="_102" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[103]" Member="_103" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[104]" Member="_104" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[105]" Member="_105" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[106]" Member="_106" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[107]" Member="_107" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[108]" Member="_108" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[109]" Member="_109" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[110]" Member="_110" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[111]" Member="_111" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[112]" Member="_112" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[113]" Member="_113" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[114]" Member="_114" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[115]" Member="_115" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[116]" Member="_116" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[117]" Member="_117" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[118]" Member="_118" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[119]" Member="_119" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[120]" Member="_120" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[121]" Member="_121" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[122]" Member="_122" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[123]" Member="_123" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[124]" Member="_124" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[125]" Member="_125" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[126]" Member="_126" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[127]" Member="_127" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[128]" Member="_128" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[129]" Member="_129" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[130]" Member="_130" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[131]" Member="_131" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[132]" Member="_132" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[133]" Member="_133" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[134]" Member="_134" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[135]" Member="_135" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[136]" Member="_136" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[137]" Member="_137" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[138]" Member="_138" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[139]" Member="_139" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[140]" Member="_140" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[141]" Member="_141" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[142]" Member="_142" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[143]" Member="_143" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[144]" Member="_144" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[145]" Member="_145" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[146]" Member="_146" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[147]" Member="_147" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[148]" Member="_148" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[149]" Member="_149" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[150]" Member="_150" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[151]" Member="_151" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[152]" Member="_152" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[153]" Member="_153" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[154]" Member="_154" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[155]" Member="_155" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[156]" Member="_156" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[157]" Member="_157" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[158]" Member="_158" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[159]" Member="_159" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[160]" Member="_160" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[161]" Member="_161" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[162]" Member="_162" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[163]" Member="_163" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[164]" Member="_164" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[165]" Member="_165" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[166]" Member="_166" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[167]" Member="_167" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[168]" Member="_168" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[169]" Member="_169" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[170]" Member="_170" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[171]" Member="_171" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[172]" Member="_172" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[173]" Member="_173" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[174]" Member="_174" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[175]" Member="_175" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[176]" Member="_176" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[177]" Member="_177" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[178]" Member="_178" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[179]" Member="_179" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[180]" Member="_180" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[181]" Member="_181" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[182]" Member="_182" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[183]" Member="_183" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[184]" Member="_184" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[185]" Member="_185" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[186]" Member="_186" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[187]" Member="_187" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[188]" Member="_188" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[189]" Member="_189" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[190]" Member="_190" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[191]" Member="_191" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[192]" Member="_192" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[193]" Member="_193" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[194]" Member="_194" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[195]" Member="_195" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[196]" Member="_196" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[197]" Member="_197" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[198]" Member="_198" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[199]" Member="_199" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[200]" Member="_200" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[201]" Member="_201" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[202]" Member="_202" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[203]" Member="_203" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[204]" Member="_204" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[205]" Member="_205" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[206]" Member="_206" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[207]" Member="_207" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[208]" Member="_208" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[209]" Member="_209" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[210]" Member="_210" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[211]" Member="_211" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[212]" Member="_212" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[213]" Member="_213" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[214]" Member="_214" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[215]" Member="_215" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[216]" Member="_216" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[217]" Member="_217" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[218]" Member="_218" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[219]" Member="_219" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[220]" Member="_220" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[221]" Member="_221" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[222]" Member="_222" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[223]" Member="_223" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[224]" Member="_224" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[225]" Member="_225" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[226]" Member="_226" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[227]" Member="_227" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[228]" Member="_228" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[229]" Member="_229" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[230]" Member="_230" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[231]" Member="_231" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[232]" Member="_232" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[233]" Member="_233" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[234]" Member="_234" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[235]" Member="_235" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[236]" Member="_236" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[237]" Member="_237" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[238]" Member="_238" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[239]" Member="_239" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[240]" Member="_240" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[241]" Member="_241" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[242]" Member="_242" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[243]" Member="_243" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[244]" Member="_244" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[245]" Member="_245" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[246]" Member="_246" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[247]" Member="_247" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[248]" Member="_248" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[249]" Member="_249" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[250]" Member="_250" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[251]" Member="_251" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[252]" Member="_252" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[253]" Member="_253" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[254]" Member="_254" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[255]" Member="_255" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[256]" Member="_256" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[257]" Member="_257" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[258]" Member="_258" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[259]" Member="_259" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[260]" Member="_260" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[261]" Member="_261" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[262]" Member="_262" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[263]" Member="_263" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[264]" Member="_264" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[265]" Member="_265" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SH_Analysis" Member="SH_Analysis">
    <Type Name="SH_Analysi">
      <Column Name="Record_ID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PartNumber" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="ArrayNumber" Type="System.String" DbType="NVarChar(13)" CanBeNull="true" />
      <Column Name="Col" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Row" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="StartDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AnalysisDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AnalysisVersion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PassFailCode" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Measurement_Grade" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ROP_0_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ROP_0_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ROP_0_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="RMS_0_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="RMS_0_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="RMS_0_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ROP_inf_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ROP_inf_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ROP_inf_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="RMS_inf_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="RMS_inf_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="RMS_inf_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP_Power_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP_Power_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP_Power_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP_RMS_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP_RMS_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP_RMS_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP_Volt_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP_Volt_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP_Volt_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP_Freq_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP_Freq_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP_Freq_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP25_Power_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP25_Power_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP25_Power_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP25_RMS_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP25_RMS_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP25_RMS_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP25_Volt_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP25_Volt_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP25_Volt_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP25_Freq_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP25_Freq_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP25_Freq_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP20_Power_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP20_Power_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP20_Power_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP20_RMS_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP20_RMS_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP20_RMS_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP20_Volt_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP20_Volt_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP20_Volt_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP20_Freq_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP20_Freq_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP20_Freq_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP15_Power_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP15_Power_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP15_Power_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP15_RMS_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP15_RMS_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP15_RMS_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP15_Volt_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP15_Volt_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP15_Volt_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP15_Freq_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP15_Freq_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ClearOP15_Freq_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PeakOP_Power_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PeakOP_Power_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PeakOP_Power_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PeakOP_RMS_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PeakOP_RMS_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PeakOP_RMS_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PeakOP_Volt_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PeakOP_Volt_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PeakOP_Volt_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PeakOP_Freq_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PeakOP_Freq_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PeakOP_Freq_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I8Dp_Volt_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I8Dp_Volt_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I8Dp_Volt_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I10Dp_Freq_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I10Dp_Freq_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I10Dp_Freq_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I10Dp_RMS_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I10Dp_RMS_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I10Dp_RMS_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I8Dp_Freq_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I8Dp_Freq_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I8Dp_Freq_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I8Dp_RMS_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I8Dp_RMS_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I8Dp_RMS_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I08Dpt0_Volt_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I08Dpt0_Volt_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I08Dpt0_Volt_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I08Dpt0_Freq_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I08Dpt0_Freq_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I08Dpt0_Freq_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I08Dpt0_RMS_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I08Dpt0_RMS_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I08Dpt0_RMS_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I08Dptinf_Freq_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I08Dptinf_Freq_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I08Dptinf_Freq_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I08Dptinf_RMS_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I08Dptinf_RMS_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I08Dptinf_RMS_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I10Dpt0_Freq_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I10Dpt0_Freq_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I10Dpt0_Freq_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I10Dpt0_RMS_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I10Dpt0_RMS_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I10Dpt0_RMS_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I10Dptinf_Freq_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I10Dptinf_Freq_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I10Dptinf_Freq_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I10Dptinf_RMS_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I10Dptinf_RMS_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I10Dptinf_RMS_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PeakOPfit_Power_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PeakOPfit_Power_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PeakOPfit_Power_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PeakOPfit_RMS_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PeakOPfit_RMS_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PeakOPfit_RMS_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PeakOPfit_Freq_avg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PeakOPfit_Freq_H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PeakOPfit_Freq_V" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Polarization_Offset" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="RMS_Delta_Polar_Power" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Max_Delta_Polar_Power_12D" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Future_1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Future_2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Future_3" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Future_4" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_Analysis_List" Member="v_Analysis_Lists">
    <Type Name="v_Analysis_List">
      <Column Name="Record_ID" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ArrayNumber" Type="System.String" DbType="NVarChar(13)" CanBeNull="true" />
      <Column Name="PartNumber" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="StartDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateDif" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ALF_Data_MES" Member="ALF_Data_MEs">
    <Type Name="ALF_Data_ME">
      <Column Name="Record_ID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MeasurementsSuiteID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PartID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PartNumber" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="ArrayNumber" Type="System.String" DbType="NVarChar(13)" CanBeNull="true" />
      <Column Name="PassFailCode" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SiteID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OperatorID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DOYNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="StartDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[06]" Member="_06" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[07]" Member="_07" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[08]" Member="_08" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[09]" Member="_09" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[10]" Member="_10" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[11]" Member="_11" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[12]" Member="_12" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[13]" Member="_13" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[14]" Member="_14" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[15]" Member="_15" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[16]" Member="_16" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[17]" Member="_17" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[18]" Member="_18" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[19]" Member="_19" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[20]" Member="_20" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[21]" Member="_21" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[22]" Member="_22" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[23]" Member="_23" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[24]" Member="_24" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[25]" Member="_25" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[26]" Member="_26" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[27]" Member="_27" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[28]" Member="_28" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[29]" Member="_29" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[30]" Member="_30" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[31]" Member="_31" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[32]" Member="_32" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[33]" Member="_33" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[34]" Member="_34" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[35]" Member="_35" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[36]" Member="_36" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[37]" Member="_37" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[38]" Member="_38" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[39]" Member="_39" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[40]" Member="_40" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[41]" Member="_41" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[42]" Member="_42" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[43]" Member="_43" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[44]" Member="_44" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[45]" Member="_45" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[46]" Member="_46" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[47]" Member="_47" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[48]" Member="_48" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[49]" Member="_49" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[50]" Member="_50" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[51]" Member="_51" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[52]" Member="_52" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[53]" Member="_53" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[54]" Member="_54" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[55]" Member="_55" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[56]" Member="_56" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[57]" Member="_57" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[58]" Member="_58" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[59]" Member="_59" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[60]" Member="_60" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[61]" Member="_61" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[62]" Member="_62" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[63]" Member="_63" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[64]" Member="_64" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[65]" Member="_65" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[66]" Member="_66" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[67]" Member="_67" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[68]" Member="_68" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[69]" Member="_69" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[70]" Member="_70" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[71]" Member="_71" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[72]" Member="_72" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[73]" Member="_73" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[74]" Member="_74" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[75]" Member="_75" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[76]" Member="_76" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[77]" Member="_77" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[78]" Member="_78" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[79]" Member="_79" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[80]" Member="_80" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[81]" Member="_81" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[82]" Member="_82" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[83]" Member="_83" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[84]" Member="_84" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[85]" Member="_85" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[86]" Member="_86" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[87]" Member="_87" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[88]" Member="_88" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[89]" Member="_89" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[90]" Member="_90" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[91]" Member="_91" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[92]" Member="_92" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[93]" Member="_93" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[94]" Member="_94" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[95]" Member="_95" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[96]" Member="_96" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[97]" Member="_97" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[98]" Member="_98" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[99]" Member="_99" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[100]" Member="_100" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[101]" Member="_101" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[102]" Member="_102" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[103]" Member="_103" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[104]" Member="_104" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[105]" Member="_105" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[106]" Member="_106" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[107]" Member="_107" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[108]" Member="_108" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[109]" Member="_109" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[110]" Member="_110" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[111]" Member="_111" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[112]" Member="_112" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[113]" Member="_113" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[114]" Member="_114" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[115]" Member="_115" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[116]" Member="_116" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[117]" Member="_117" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[118]" Member="_118" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[119]" Member="_119" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[120]" Member="_120" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[121]" Member="_121" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[122]" Member="_122" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[123]" Member="_123" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[124]" Member="_124" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[125]" Member="_125" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[126]" Member="_126" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[127]" Member="_127" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[128]" Member="_128" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[129]" Member="_129" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[130]" Member="_130" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[131]" Member="_131" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[132]" Member="_132" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[133]" Member="_133" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[134]" Member="_134" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[135]" Member="_135" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[136]" Member="_136" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[137]" Member="_137" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[138]" Member="_138" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[139]" Member="_139" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[140]" Member="_140" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[141]" Member="_141" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[142]" Member="_142" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[143]" Member="_143" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[144]" Member="_144" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[145]" Member="_145" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[146]" Member="_146" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[147]" Member="_147" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[148]" Member="_148" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[149]" Member="_149" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[150]" Member="_150" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[151]" Member="_151" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[152]" Member="_152" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[153]" Member="_153" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[154]" Member="_154" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[155]" Member="_155" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[156]" Member="_156" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[157]" Member="_157" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[158]" Member="_158" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[159]" Member="_159" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[160]" Member="_160" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[161]" Member="_161" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[162]" Member="_162" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[163]" Member="_163" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[164]" Member="_164" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[165]" Member="_165" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[166]" Member="_166" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[167]" Member="_167" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[168]" Member="_168" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[169]" Member="_169" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[170]" Member="_170" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[171]" Member="_171" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[172]" Member="_172" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[173]" Member="_173" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[174]" Member="_174" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[175]" Member="_175" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[176]" Member="_176" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[177]" Member="_177" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[178]" Member="_178" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[179]" Member="_179" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[180]" Member="_180" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[181]" Member="_181" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[182]" Member="_182" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[183]" Member="_183" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[184]" Member="_184" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[185]" Member="_185" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[186]" Member="_186" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[187]" Member="_187" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[188]" Member="_188" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[189]" Member="_189" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[190]" Member="_190" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[191]" Member="_191" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[192]" Member="_192" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[193]" Member="_193" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[194]" Member="_194" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[195]" Member="_195" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[196]" Member="_196" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[197]" Member="_197" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[198]" Member="_198" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[199]" Member="_199" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[200]" Member="_200" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[201]" Member="_201" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[202]" Member="_202" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[203]" Member="_203" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[204]" Member="_204" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[205]" Member="_205" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[206]" Member="_206" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[207]" Member="_207" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[208]" Member="_208" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[209]" Member="_209" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[210]" Member="_210" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[211]" Member="_211" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[212]" Member="_212" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[213]" Member="_213" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[214]" Member="_214" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[215]" Member="_215" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[216]" Member="_216" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[217]" Member="_217" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[218]" Member="_218" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[219]" Member="_219" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[220]" Member="_220" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[221]" Member="_221" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[222]" Member="_222" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[223]" Member="_223" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[224]" Member="_224" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[225]" Member="_225" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[226]" Member="_226" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[227]" Member="_227" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[228]" Member="_228" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[229]" Member="_229" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[230]" Member="_230" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[231]" Member="_231" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[232]" Member="_232" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[233]" Member="_233" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[234]" Member="_234" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[235]" Member="_235" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[236]" Member="_236" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[237]" Member="_237" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[238]" Member="_238" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[239]" Member="_239" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[240]" Member="_240" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[241]" Member="_241" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[242]" Member="_242" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[243]" Member="_243" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[244]" Member="_244" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[245]" Member="_245" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[246]" Member="_246" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[247]" Member="_247" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[248]" Member="_248" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[249]" Member="_249" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[250]" Member="_250" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[251]" Member="_251" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[252]" Member="_252" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[253]" Member="_253" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[254]" Member="_254" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[255]" Member="_255" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[256]" Member="_256" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[257]" Member="_257" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[258]" Member="_258" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[259]" Member="_259" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[260]" Member="_260" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[261]" Member="_261" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[262]" Member="_262" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[263]" Member="_263" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[264]" Member="_264" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[265]" Member="_265" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[266]" Member="_266" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[267]" Member="_267" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[268]" Member="_268" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[269]" Member="_269" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[270]" Member="_270" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[271]" Member="_271" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[272]" Member="_272" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[273]" Member="_273" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[274]" Member="_274" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[275]" Member="_275" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[276]" Member="_276" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[277]" Member="_277" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[278]" Member="_278" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[279]" Member="_279" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_Analysis_Work_List" Member="v_Analysis_Work_Lists">
    <Type Name="v_Analysis_Work_List">
      <Column Name="Record_ID" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ArrayNumber" Type="System.String" DbType="NVarChar(13)" CanBeNull="true" />
      <Column Name="PartNumber" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="StartDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="FreqPower" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
</Database>